name: 03 event filter

on:
  pull_request:
    types:
      - closed
    # types: [closed,reopen]
  push:
    paths:
      - "ci-cd/routes/web.php"

jobs:
  say-hi-to-me:
    runs-on: ubuntu-latest
    steps:
      - name:
        run: echo "event filter"
