name: 04-basics-event-filter-2

on:
  # pull_request:
  #   types:
  #     - reopened
  #   # branches:
  #   #   - master
  #   branches-ignore:
  #     - master
  push:
    # tags: [v2]
    # tags-ignore: [v1]
    paths:
      - "ci-cd/routes/web.php"

jobs:
  forepoen:
    runs-on: ubuntu-latest
    steps:
      - name: s1
        run: echo 'hi from reopen'
