name: 04-basics-event-filter-2

on:
  pull_request:
    types:
      - reopened
    # branches:
    #   - master
    branches-ignore:
      - master
  push:
    branches-ignore: [master, main]

jobs:
  forepoen:
    runs-on: ubuntu-latest
    steps:
      - name: s1
        run: echo 'hi from reopen'
