name: 05 context

run-name: ${{ github.actor }} ${{github.run_number}}th try

env:
  MY_NAME: "ABDALRHMAN"

on:
  push:

jobs:
  weclome-to-me:
    runs-on: ubuntu-latest
    env:
      MY_NAME2: "firas"
    steps:
      - name: check1
        run: echo ${{env.MY_NAME}}

      - name: check2
        if: ${{ github.run_number >= 10 }}
        run: echo ${{env.MY_NAME2}}
