name: 05 context

run-name: ${{ github.actor }} ${{github.run_number}}th try

on:
  push:

jobs:
  weclome-to-me:
    runs-on: ubuntu-latest
    steps:
      - name:
        run: echo ${{ toJson(github) }}
