name: 05 context

run-name: ${{ github.actor }} ${{github.run_number}}th try

on:
  push:

jobs:
  weclome-to-me:
    runs-on: ubuntu-latest
    steps:
      - name: check1
        run: echo 'berfore the conditions'
        if: github.run_number = 10
      - name: check2
        run: echo ${{github.run_number th}}
