name: 01 first workflow

on: workflow_dispatch

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: print-hello-world
        run: echo "hello world"

      - name: step 2
        run: echo "hi guys"

  say-hi-to-me:
    runs-on: ubuntu-latest
    steps:
      - name:
        run: echo "hi abd"
